apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: snoop2021/auth
          env:
            - name: MONGO_URI
              value: "mongodb+srv://authapi:auth@cluster0.2f6yqbj.mongodb.net"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: auth-depl
spec:
  selector:
    app: auth
  ports:
    - port: 3000
      targetPort: 3000
