apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: snoop2021/payments
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: shopping
            - name: MONGO_URI
              value: "mongodb+srv://paymentapi:payment@cluster0.txe4zfx.mongodb.net"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIP_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIP_KEY
            - name: PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: braintree-public-secret
                  key: PUBLIC_KEY
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: braintree-private-secret
                  key: PRIVATE_KEY
            - name: MERCHANT_ID
              valueFrom:
                secretKeyRef:
                  name: braintree-merchant-id
                  key: MERCHANT_ID

---
apiVersion: v1
kind: Service
metadata:
  name: payments-depl
spec:
  selector:
    app: payments
  ports:
    - port: 3000
      targetPort: 3000
